### ISSUE TITLE
Renaming the repository to `MMM-Facts`

### ISSUE THREAD

**Issue by dennisklad** [alanshen111/facts#3]
Firstly, thanks so much for the code! I love the module and have been using it some time ;) 

Maybe a little reaching, I am sorry, but could you please rename the repository to `MMM-Facts` to be easier to find and more uniform with the rest of the community? 

Thanks in advance. :)

**Comment by alanshen111** [comment]
Thanks for raising the issue! That's a great idea. Sorry I was inactive.
